spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/firstbase
    username: postgres
    password: yasso
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081